import { generateFiles } from '@/lib/builder/codegen';
import { fromSearchParams } from '@/lib/builder/encode';
import { overridesDates } from '@/lib/builder/types';
import { getKit } from '@/lib/registry';
import { readKitFiles } from '@/lib/registry-files';

/**
 * The setup flow's install endpoint — `/r/init.json?kit=…&perPageKey=…`.
 *
 * Dynamic, unlike the per-kit endpoints next door: the chosen setup arrives in
 * the query string, so a command generated by the flow needs nothing stored on
 * our side and still works months later in a README. Unknown or malformed
 * params fall back to the library's defaults rather than failing, so a
 * hand-edited URL degrades to a stock setup instead of an error.
 *
 * The literal `init.json` segment takes precedence over the sibling `[item]`
 * route, which stays statically generated for the plain per-kit items.
 */

export const dynamic = 'force-dynamic';

export async function GET(request: Request) {
  const config = fromSearchParams(new URL(request.url).searchParams);
  const kit = config.kit === 'none' ? undefined : getKit(config.kit);

  const generated = generateFiles(config).map((file) => ({
    content: file.content,
    path: `registry/init/${file.name}`,
    target: file.target,
    type: file.registryType
  }));

  // date-fns is only needed when a custom date format is emitted; the kits that
  // use it already declare it themselves.
  const dependencies = new Set(kit?.dependencies ?? ['@mbsatimov/use-filters', 'nuqs']);
  if (overridesDates(config)) dependencies.add('date-fns');

  return Response.json(
    {
      $schema: 'https://ui.shadcn.com/schema/registry-item.json',
      dependencies: [...dependencies],
      description: kit
        ? `use-filters configured for this project, with the ${kit.title} kit.`
        : 'use-filters configured for this project.',
      files: [...(kit ? await readKitFiles(kit) : []), ...generated],
      name: 'use-filters-setup',
      registryDependencies: kit?.registryDependencies ?? [],
      title: 'use-filters setup',
      type: 'registry:component'
    },
    { headers: { 'cache-control': 'public, max-age=0, s-maxage=3600' } }
  );
}
